# Generated by Django 4.1.7 on 2023-03-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handmade_watercolors', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handmade_watercolors.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handmade_watercolors.product')),
            ],
        ),
    ]
