# Generated by Django 4.1.7 on 2023-03-19 18:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade_watercolors', '0008_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=250, null=True),
        ),
    ]
