# Generated by Django 4.1.7 on 2023-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade_watercolors', '0010_cartitem_price_alter_productreview_rating_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
