# Generated by Django 4.1.7 on 2023-03-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmade_watercolors', '0013_alter_productreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
